version: "3"
services:
  nginx:
    image: machorgua/site
    volumes:
      - "./nginx/logs:/var/log/nginx"
    expose:
      - 80
    env_file:
      - .env
networks:
  default:
    external:
      name: nginx-proxy